### PR TITLE
Add functionality to indicate alternate language pages in sitemap

### PR DESCRIPTION
**Pull request by Twissi**
I would like to add the functionality to indicate alternate language pages in sitemap.
For example:
<xhtml:link rel="alternate" hreflang="de" href="http://www.example.com/deutsch/" />

Described here:
https://support.google.com/webmasters/answer/2620865?hl=en

### CODE REVIEW

**Comment by hex7c0** [comment]
hey Kristin
thanks for this pull request, looks great!

Can you write some documentation for README file?

**Comment by Twissi** [comment]
Yeah sure!

**Comment by Twissi** [comment]
Added doc for README.

**Comment by hex7c0** [comment]
perfect :+1: 
I'm waiting for DDOS mitigation on GitHub, after that I'll merge this PR

**Pull request merged**
